import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

/* ── Article data ─────────────────────────────────────────────────── */
const ARTICLES: Record<string, {
  slug: string;
  tag: string;
  title: string;
  dek: string;
  date: string;
  read: string;
  gradient: string;
  lead: string;
  body: string; /* raw HTML */
  pullquote?: string;
  figure?: { caption: string };
  sources: string[];
  related: { slug: string; tag: string; title: string; read: string; date: string; gradient: string }[];
}> = {
  "resale-platforms-unit-economics": {
    slug: "resale-platforms-unit-economics",
    tag: "Business models",
    title: "Resale platforms and the unit economics that determine whether the model works at scale",
    dek: "Peer-to-peer luxury resale has demonstrated product-market fit in the upper segment. The question is whether the cost structure, authentication above all, scales into lower-margin categories without destroying the economics.",
    date: "12 May 2026",
    read: "8 min read",
    gradient: "linear-gradient(135deg,#141414,#222)",
    lead: "Authentication overhead is the defining cost of luxury resale. At an average of 12–18 percent of GMV, it is the cost that determines whether the model works, and it is fixed per item regardless of the item's price. That is the number everything else flows from.",
    body: `<p class="article-page__text">Vestiaire Collective, Vinted, and the cohort of platforms that followed them into peer-to-peer resale built their initial traction on the luxury segment because the economics work there. A €1,200 bag justifies €180 in authentication cost. The same infrastructure applied to a €60 dress produces a model that cannot survive.</p>

<h2 class="article-page__h2">The mid-market expansion problem</h2>

<p class="article-page__text">Most platforms' growth plans require moving down-market. Luxury inventory is finite and the auction for it is increasingly competitive. The mid-market, garments priced €50 to €300, represents the volume that would justify the fixed costs of logistics, authentication systems, and customer acquisition. The problem is that the unit economics do not follow the inventory there.</p>

<p class="article-page__text">Platforms entering this segment face a structural mismatch: authentication overhead remains constant at the item level while the revenue generated by each item falls. Take-rate compression at lower price points is not a temporary problem to be solved by scale; it is an inherent feature of the cost structure.</p>

<h2 class="article-page__h2">Network effects and the retention gap</h2>

<p class="article-page__text">Network effects in resale accumulate on the supply side. A platform with more sellers attracts more buyers and creates a self-reinforcing dynamic in inventory depth and selection. The less-discussed side of this is demand-side retention, which remains the unsolved problem for every platform in the category.</p>

<p class="article-page__text">Repeat purchase rates in resale are structurally lower than in primary retail because the supply side is unpredictable. A buyer who finds what they want today cannot guarantee a similar supply next month. That unpredictability limits the subscription logic that would make retention economics work.</p>

<h2 class="article-page__h2">Revenue mix and long-run profitability</h2>

<p class="article-page__text">The platforms that have moved closest to profitability have done so by shifting the revenue mix away from pure take-rate toward fulfilment services, packaging, shipping, and returns processing, where the margin structure is more predictable and the cost base scales with volume rather than item value. This is the model that survives the mid-market expansion; it is not the model that most platforms launched with.</p>`,
    pullquote: "\"The economics of luxury resale depend on a cost structure that does not compress as the market expands. That is not a transition problem. It is the model.\"",
    figure: { caption: "Vestiaire Collective authentication centre, Paris. Each item is inspected individually before listing — the fixed cost that defines the model's economics." },
    sources: [
      "Vestiaire Collective, Annual disclosure 2024",
      "Vinted, Investor presentation 2025",
      "BCG, The Recommerce Opportunity report, 2024",
      "Euromonitor, Secondhand Apparel 2025",
      "Company financial filings and interview notes",
    ],
    related: [
      { slug: "espr-fast-product-cycles", tag: "Regulation", title: "What ESPR means for brands that built their model on fast product cycles", read: "11 min read", date: "5 May 2026", gradient: "linear-gradient(135deg,#0e0e0e,#1c1c1c)" },
      { slug: "valuation-correction", tag: "Capital", title: "The valuation correction in sustainable fashion and what it reveals about investor assumptions", read: "12 min read", date: "14 Apr 2026", gradient: "linear-gradient(135deg,#131313,#1d1d1d)" },
      { slug: "rental-fashion-platforms", tag: "Business models", title: "Rental fashion platforms rebuilding their unit economics after the post-pandemic contraction", read: "9 min read", date: "20 Apr 2026", gradient: "linear-gradient(135deg,#090909,#181818)" },
    ],
  },

  "espr-fast-product-cycles": {
    slug: "espr-fast-product-cycles",
    tag: "Regulation",
    title: "What ESPR means for brands that built their model on fast product cycles",
    dek: "The Ecodesign for Sustainable Products Regulation imposes minimum durability, repairability, and recyclability requirements that are structurally incompatible with high-volume, low-cost product development. The brands most exposed are those whose competitive position depends on speed and volume.",
    date: "5 May 2026",
    read: "11 min read",
    gradient: "linear-gradient(135deg,#121212,#1e1e1e)",
    lead: "ESPR's durability standards require minimum component lifespans incompatible with current fast-fashion lead times. The regulation is in force. The delegated acts that set product-specific requirements are in preparation. Brands that have not begun redesign work are already behind.",
    body: `<p class="article-page__text">The Ecodesign for Sustainable Products Regulation entered into force in July 2024. Its immediate effect was a ban on the destruction of unsold apparel and footwear for large companies from 19 July 2026. The more consequential effect, which is still being written into law through delegated acts, is a set of minimum performance requirements for products placed on the EU market.</p>

<h2 class="article-page__h2">What the regulation actually requires</h2>

<p class="article-page__text">ESPR creates a framework for product-specific ecodesign requirements. For textiles, the delegated acts will set minimum standards on durability, repairability, and recyclability. Durability standards require minimum component lifespans. Repairability requirements will raise unit costs for brands whose margins depend on non-serviceable construction. Non-compliant products face market withdrawal — a binary outcome, not a fine.</p>

<p class="article-page__text">The estimated redesign cost per SKU under ESPR durability requirements is €8k–€24k depending on the product category and the degree of non-compliance in the existing design. For brands with catalogues running to thousands of SKUs, the aggregate cost is material. The brands with the least runway are those still investing in new SKU development without factoring in compliance costs.</p>

<h2 class="article-page__h2">Which business models face structural exposure</h2>

<p class="article-page__text">Fast fashion's competitive model depends on speed and volume. High SKU counts, short development cycles, and low per-unit investment are the defining features. ESPR's durability requirements are structurally incompatible with this approach. A garment designed to be worn 10 times cannot meet minimum lifespan requirements for a product designed to be worn 30 or 40 times. The engineering required to meet the standard is incompatible with the development timeline and per-unit budget that makes the current model viable.</p>

<p class="article-page__text">Compliance timeline varies by product category; phased exposure is the real planning challenge. Brands entering delegated act consultation windows now have an opportunity to shape the final requirements. Brands that wait for the final text lose that opportunity and inherit the compliance cost with less lead time.</p>

<h2 class="article-page__h2">The Digital Product Passport connection</h2>

<p class="article-page__text">ESPR also enables Digital Product Passport requirements via delegated acts. The DPP mandate will require brands to make product composition, repairability, and recyclability data accessible at the product level via QR or NFC. This is not a marketing exercise; it is a disclosure requirement with enforcement. Brands that have not built supply chain data infrastructure will face a second compliance cost alongside the product redesign requirement.</p>`,
    pullquote: "\"Non-compliant products face market withdrawal: a binary outcome, not a fine. That changes the planning calculus entirely.\"",
    sources: [
      "European Commission — ESPR Regulation text (EU) 2024/1781",
      "EURATEX — Industry impact assessment 2025",
      "H&M Group — Sustainability report 2024",
      "Zara / Inditex — Annual report 2024",
    ],
    related: [
      { slug: "csrd-reporting-burden", tag: "Regulation", title: "The CSRD reporting burden and what it actually costs a mid-size fashion brand to comply", read: "15 min read", date: "5 May 2026", gradient: "linear-gradient(135deg,#0a0a0a,#1e1e1e)" },
      { slug: "resale-platforms-unit-economics", tag: "Business models", title: "Resale platforms and the unit economics that determine whether the model works at scale", read: "8 min read", date: "12 May 2026", gradient: "linear-gradient(135deg,#141414,#222)" },
      { slug: "valuation-correction", tag: "Capital", title: "The valuation correction in sustainable fashion and what it reveals about investor assumptions", read: "12 min read", date: "14 Apr 2026", gradient: "linear-gradient(135deg,#131313,#1d1d1d)" },
    ],
  },

  "consumer-behaviour-gap": {
    slug: "consumer-behaviour-gap",
    tag: "Consumer behaviour",
    title: "The gap between stated intention and purchasing behaviour in sustainable fashion",
    dek: "Consumer surveys consistently overstate willingness to pay for sustainable products. The purchasing data tells a different story. This piece analyses the gap between stated and revealed preference and what it means for the commercial viability of sustainability-positioned brands.",
    date: "28 Apr 2026",
    read: "14 min read",
    gradient: "linear-gradient(135deg,#0e0e0e,#1a1a1a)",
    lead: "The intention-action gap in sustainable fashion purchasing is structurally larger than in food or personal care. Consumers state a willingness to pay a 28% premium for verified sustainability credentials. The observed figure at checkout is 7–12%. The difference between those two numbers is the commercial problem the sector has not solved.",
    body: `<p class="article-page__text">Survey data on consumer sustainability preferences has been misread as market signal for the better part of a decade. The research consistently finds high stated intention to buy sustainably, high stated willingness to pay a premium, and high stated concern about environmental and social conditions in supply chains. The sales data from the same period tells a different story.</p>

<h2 class="article-page__h2">What the purchasing data shows</h2>

<p class="article-page__text">Price sensitivity at checkout erodes the stated 28% premium to an observed 7–12%. Verification and certification labels increase conversion marginally but do not close the gap. The intention-action gap is not a measurement artifact; it is a structural feature of how consumers make decisions under budget constraints. Stated preferences reflect aspirational identity. Revealed preferences reflect actual trade-offs.</p>

<p class="article-page__text">Segment analysis shows the gap narrows significantly in professional, high-income demographics. The willingness-to-pay premium is real in this segment. The commercial problem is that this segment is not large enough to support the growth plans of most sustainability-positioned brands, and reaching the mass market requires a different proposition.</p>

<h2 class="article-page__h2">The certification problem</h2>

<p class="article-page__text">The proliferation of sustainability certifications has not solved the credibility problem; it has compounded it. Consumers exposed to multiple competing certification schemes show lower trust in all of them compared to consumers in markets with fewer schemes. The signal has been diluted by volume. The Green Claims Directive, if it advances, would impose pre-verification requirements that reduce the number of active claims in the market. The effect on consumer trust is an open empirical question.</p>

<h2 class="article-page__h2">Implications for brand strategy</h2>

<p class="article-page__text">The brands that have closed the intention-action gap most effectively have done so not by making sustainability the primary purchase driver but by making it an attribute of a product that wins on primary drivers — design, fit, quality, or price. The sustainability claim is a secondary reason to prefer, not the primary reason to buy. This is a different positioning strategy and a different communication strategy from the one most sustainability-positioned brands have pursued.</p>`,
    pullquote: "\"Price sensitivity at checkout erodes the stated 28% premium to 7–12%. That gap is the commercial problem the sector has not solved.\"",
    sources: [
      "McKinsey — State of Fashion 2025",
      "GreenPrint — Consumer sustainability survey 2025",
      "Nielsen — Sustainability Purchase Behaviour Report",
      "Kantar — Purpose 2025 study",
    ],
    related: [
      { slug: "valuation-correction", tag: "Capital", title: "The valuation correction in sustainable fashion and what it reveals about investor assumptions", read: "12 min read", date: "14 Apr 2026", gradient: "linear-gradient(135deg,#131313,#1d1d1d)" },
      { slug: "espr-fast-product-cycles", tag: "Regulation", title: "What ESPR means for brands that built their model on fast product cycles", read: "11 min read", date: "5 May 2026", gradient: "linear-gradient(135deg,#121212,#1e1e1e)" },
      { slug: "resale-platforms-unit-economics", tag: "Business models", title: "Resale platforms and the unit economics that determine whether the model works at scale", read: "8 min read", date: "12 May 2026", gradient: "linear-gradient(135deg,#141414,#222)" },
    ],
  },

  "csrd-reporting-burden": {
    slug: "csrd-reporting-burden",
    tag: "Regulation",
    title: "The CSRD reporting burden and what it actually costs a mid-size fashion brand to comply",
    dek: "The CSRD creates a two-speed market inside fashion: incumbents with existing NFRD infrastructure absorb it at marginal cost, while mid-size brands face a step-change in fixed overhead that changes their unit economics before the first report is filed.",
    date: "5 May 2026",
    read: "15 min read",
    gradient: "linear-gradient(135deg,#0a0a0a,#1e1e1e)",
    lead: "First-year compliance costs for a mid-size fashion brand without existing CSRD infrastructure range €300k–€800k. The burden concentrates in data collection and third-party verification, not the report itself. That cost lands before revenue is generated from any market advantage compliance might create.",
    body: `<p class="article-page__text">The Corporate Sustainability Reporting Directive, as amended by Omnibus I in March 2026, narrowed scope to companies with more than 1,000 employees and more than €450M net turnover — both thresholds required. First mandatory reports are due in 2028 for FY2027. The narrowing has been widely reported as relief. It is partial relief, and it does not change the economics for the brands that remain in scope.</p>

<h2 class="article-page__h2">Where the cost actually falls</h2>

<p class="article-page__text">The compliance cost does not fall in writing the report. It falls in building the data infrastructure that makes the report possible. Brands without CSRD-grade supplier visibility face secondary exposure through large customer CSRD obligations — a wholesale customer in scope will cascade its data requirements down the supply chain regardless of the direct obligation threshold.</p>

<p class="article-page__text">First-year compliance for a mid-size brand without existing infrastructure: €300k–€800k. This breaks down approximately as follows. Data collection systems and implementation: €80k–€200k. External consultant and advisory costs: €60k–€150k. Third-party assurance: €50k–€120k. Internal staff time (FTE equivalent): €80k–€200k. Ongoing annual cost after year one: €150k–€400k.</p>

<h2 class="article-page__h2">The two-speed market</h2>

<p class="article-page__text">Compliance creates a structural cost advantage for large players over the medium term. Incumbents with existing NFRD infrastructure absorb CSRD at marginal cost. Mid-size brands facing the obligation for the first time bear the full fixed cost of building the infrastructure. That cost does not scale with revenue; a brand with €500M turnover and a brand with €5B turnover face similar absolute compliance costs but very different relative burdens.</p>

<p class="article-page__text">The brands without CSRD-grade supplier visibility face a compounding problem. Their large wholesale and retail customers — in scope for CSRD — will cascade data requests down the supply chain. Compliance with customer data requests is effectively mandatory regardless of the direct obligation. The cost of not building the infrastructure is market access risk, not just regulatory risk.</p>

<h2 class="article-page__h2">What the amended scope means in practice</h2>

<p class="article-page__text">Omnibus I narrowed the scope materially. Brands that would have been in scope under the original directive but fall below the amended thresholds have gained time. They have not gained exemption from supply chain data pressure. The practical implication is that building supplier data infrastructure remains a commercial necessity even for brands not directly in scope — the question is timing, not whether.</p>`,
    pullquote: "\"Compliance creates a structural cost advantage for large players. The cost does not scale with revenue; the burden falls disproportionately on mid-size brands.\"",
    sources: [
      "European Commission, CSRD Directive and implementing standards",
      "EFRAG — ESRS sector-specific standards consultation",
      "PwC, CSRD readiness survey 2025",
      "Company disclosures: H&M Group, Inditex, Zalando",
    ],
    related: [
      { slug: "espr-fast-product-cycles", tag: "Regulation", title: "What ESPR means for brands that built their model on fast product cycles", read: "11 min read", date: "5 May 2026", gradient: "linear-gradient(135deg,#121212,#1e1e1e)" },
      { slug: "valuation-correction", tag: "Capital", title: "The valuation correction in sustainable fashion and what it reveals about investor assumptions", read: "12 min read", date: "14 Apr 2026", gradient: "linear-gradient(135deg,#131313,#1d1d1d)" },
      { slug: "consumer-behaviour-gap", tag: "Consumer behaviour", title: "The gap between stated intention and purchasing behaviour in sustainable fashion", read: "14 min read", date: "28 Apr 2026", gradient: "linear-gradient(135deg,#0e0e0e,#1a1a1a)" },
    ],
  },

  "valuation-correction": {
    slug: "valuation-correction",
    tag: "Capital",
    title: "The valuation correction in sustainable fashion and what it reveals about investor assumptions",
    dek: "The valuation correction in sustainable fashion between 2022 and 2025 was not a sector-wide collapse. It was a recalibration of assumptions. The companies that corrected most sharply were those whose valuations had priced in a consumer transition that has not yet occurred at the pace the models required.",
    date: "14 Apr 2026",
    read: "12 min read",
    gradient: "linear-gradient(135deg,#131313,#1d1d1d)",
    lead: "Median EV/Revenue multiples for sustainability-positioned fashion companies fell 61% from 2022 peak to 2025. The correction was sharpest in companies with high customer acquisition costs and low retention. Investors are repricing growth assumptions where consumer adoption lags the business plan.",
    body: `<p class="article-page__text">The 2022–2025 valuation correction in sustainable fashion was not random. It tracked the specific assumption that had been embedded in the 2021 peak valuations: that consumer behaviour was in structural transition, that the willingness-to-pay premium for sustainability-positioned products was durable and growing, and that the brands capturing that transition would compound at the rates their multiples implied. The evidence on those assumptions has come in, and it has been mixed.</p>

<h2 class="article-page__h2">What the correction actually tells us</h2>

<p class="article-page__text">The correction was sharpest in companies with high customer acquisition costs and low retention — the combination that makes growth expensive and fragile simultaneously. B2B sustainability services, compliance infrastructure, and supply chain tooling held valuation better than consumer-facing brands. The correction was a recalibration of assumptions about consumer behaviour, not a judgment on the underlying regulatory trend, which has continued to move in the expected direction.</p>

<p class="article-page__text">The companies that corrected most sharply shared several features: consumer-facing propositions, premium price positioning, growth plans dependent on market expansion rather than market deepening, and cost structures that required volume to reach profitability. That combination is fragile when consumer adoption lags the business plan. It describes a large share of the funded cohort from 2019 to 2022.</p>

<h2 class="article-page__h2">The B2B exception</h2>

<p class="article-page__text">B2B sustainability services — compliance tooling, supply chain verification, traceability infrastructure, reporting software — have held valuation better through the correction. The demand driver for these businesses is regulatory obligation, not consumer preference. Regulatory obligation is more predictable than consumer behaviour and less susceptible to the intention-action gap that has undermined consumer-facing propositions.</p>

<p class="article-page__text">The implication for capital allocation is that the regulatory tail, which is long and increasingly detailed, supports a specific category of investment that does not depend on consumer transition. Brands that serve other brands' compliance needs are in a different risk category from brands that serve consumer aspiration.</p>

<h2 class="article-page__h2">What comes next</h2>

<p class="article-page__text">The 2026 pipeline of regulatory enforcement — ESPR destruction ban, CSRD first reports, DPP delegated acts in preparation — will convert compliance obligation into commercial demand. The companies positioned to benefit from that demand curve are in B2B supply chain infrastructure, compliance services, and materials traceability. The consumer transition may or may not accelerate; the regulatory transition is on a published schedule.</p>`,
    pullquote: "\"The correction tracked a specific assumption: that consumer behaviour was in structural transition at the pace the models required. The evidence on that assumption has come in, and it has been mixed.\"",
    sources: [
      "PitchBook — Fashion Tech & Sustainability sector data 2025",
      "Crunchbase — Funding rounds tracker",
      "Bloomberg — Sector multiples analysis",
      "Company filings: Pangaia, Allbirds, Renewlane",
    ],
    related: [
      { slug: "consumer-behaviour-gap", tag: "Consumer behaviour", title: "The gap between stated intention and purchasing behaviour in sustainable fashion", read: "14 min read", date: "28 Apr 2026", gradient: "linear-gradient(135deg,#0e0e0e,#1a1a1a)" },
      { slug: "resale-platforms-unit-economics", tag: "Business models", title: "Resale platforms and the unit economics that determine whether the model works at scale", read: "8 min read", date: "12 May 2026", gradient: "linear-gradient(135deg,#141414,#222)" },
      { slug: "espr-fast-product-cycles", tag: "Regulation", title: "What ESPR means for brands that built their model on fast product cycles", read: "11 min read", date: "5 May 2026", gradient: "linear-gradient(135deg,#121212,#1e1e1e)" },
    ],
  },

  "nearshoring-costs": {
    slug: "nearshoring-costs",
    tag: "Manufacturing",
    title: "Nearshoring costs and the trade-off between speed-to-market and carbon footprint at scale",
    dek: "Nearshoring to Southern Europe and North Africa reduces Scope 3 transport emissions and cuts lead times. It also costs significantly more. This piece maps the cost structure of nearshoring and the conditions under which the economics work.",
    date: "8 Apr 2026",
    read: "7 min read",
    gradient: "linear-gradient(135deg,#111,#1c1c1c)",
    lead: "Nearshored production in Southern Europe and North Africa carries a cost premium of 22–40% over Southeast Asia sourcing, depending on the product category. The premium is real. The question is whether the speed, flexibility, and carbon arguments justify it — and for most brands in most categories, the honest answer is that they do not.",
    body: `<p class="article-page__text">The nearshoring narrative in fashion conflates three distinct propositions: a speed-to-market argument, a carbon argument, and a resilience argument. Each is real. None of them individually, and not all of them in combination, closes the cost gap for the majority of brands in the majority of product categories. The economics work in a specific and narrow set of circumstances.</p>

<h2 class="article-page__h2">Where the premium falls</h2>

<p class="article-page__text">A 22–40% production cost premium over Southeast Asia sourcing is category-dependent. The premium is lower in high-value, complex products where labour cost is a smaller share of total cost and lead time value is higher. It is higher in commodity basics where labour cost dominates and inventory predictability makes long lead times manageable. Brands that have nearshored successfully have done so in the former category; the economics in the latter have not changed.</p>

<p class="article-page__text">Speed-to-market gains are real: 6–8 week lead time reduction versus offshore sourcing. For brands whose model depends on reaction to in-season demand signals — the fast fashion model — that reduction has genuine revenue value. For brands operating on planned buy schedules, the value of the time reduction is lower. Carbon reduction claims require Scope 3 verification; most brands currently cannot supply this.</p>

<h2 class="article-page__h2">The carbon argument</h2>

<p class="article-page__text">Transport from Southeast Asia to European markets generates measurable Scope 3 emissions. Nearshoring reduces transport emissions. The reduction is real but smaller than the marketing around it implies, because transport is a minority of total lifecycle emissions for most garments. The majority of a garment's carbon footprint sits in material production and processing, not in the transport leg. Brands that have moved production closer to market and claimed carbon reductions based on transport alone are overstating the benefit.</p>

<h2 class="article-page__h2">When the economics work</h2>

<p class="article-page__text">Brands can justify the nearshoring premium in high-turn, low-volume categories where reaction speed has direct revenue value and where the premium can be absorbed into the margin structure or passed through in price. In commodity basics, the economics do not work. The question brands need to answer is whether their margin structure can absorb the premium, whether their customer will pay a price that covers it, and whether the speed benefit actually converts to revenue. Most honest analyses of this question produce a narrower case for nearshoring than the headline narrative suggests.</p>`,
    pullquote: "\"The nearshoring premium of 22–40% over Southeast Asia is not offset by logistics savings alone. The economics work in a specific and narrow set of circumstances.\"",
    sources: [
      "McKinsey — Reshaping the Supply Chain report 2024",
      "UNCTAD — Near-shoring and trade report",
      "ILO — Manufacturing wage benchmarks 2025",
      "Brand interviews and sourcing data",
    ],
    related: [
      { slug: "espr-fast-product-cycles", tag: "Regulation", title: "What ESPR means for brands that built their model on fast product cycles", read: "11 min read", date: "5 May 2026", gradient: "linear-gradient(135deg,#121212,#1e1e1e)" },
      { slug: "csrd-reporting-burden", tag: "Regulation", title: "The CSRD reporting burden and what it actually costs a mid-size fashion brand to comply", read: "15 min read", date: "5 May 2026", gradient: "linear-gradient(135deg,#0a0a0a,#1e1e1e)" },
      { slug: "valuation-correction", tag: "Capital", title: "The valuation correction in sustainable fashion and what it reveals about investor assumptions", read: "12 min read", date: "14 Apr 2026", gradient: "linear-gradient(135deg,#131313,#1d1d1d)" },
    ],
  },

  "rental-fashion-platforms": {
    slug: "rental-fashion-platforms",
    tag: "Business models",
    title: "Rental fashion platforms rebuilding their unit economics after the post-pandemic contraction",
    dek: "Rental fashion platforms entered the pandemic with growth-stage unit economics and exited it with a retention crisis. The ones still operating have rebuilt their models around a narrower customer profile with higher engagement.",
    date: "20 Apr 2026",
    read: "9 min read",
    gradient: "linear-gradient(135deg,#090909,#181818)",
    lead: "Post-pandemic rental platforms average 4.2 items per subscriber per month to reach contribution margin break-even. That is the number the model rebuilds around. Customer lifetime value models have been rebuilt around subscription tenure, not acquisition volume. The economics require a different customer than the pandemic acquisition wave produced.",
    body: `<p class="article-page__text">Rental fashion entered the pandemic period with rapid subscriber growth fuelled by the same consumer behaviour patterns — aspiration, occasion dressing, wardrobe experimentation — that its model was built around. The lockdown collapse in occasion wear demand exposed the fragility of a model whose revenue per subscriber depended on a specific use case. The platforms that survived that contraction did so by making fundamental changes to their economics rather than waiting for demand to return.</p>

<h2 class="article-page__h2">The retention problem</h2>

<p class="article-page__text">Customer lifetime value models have been rebuilt around subscription tenure, not acquisition volume. The shift reflects what the post-pandemic data showed: the high-acquisition-cost cohorts acquired during growth periods had lower tenure and lower items-per-month than the organic cohorts that preceded them. The economics of rental, unlike most subscription models, are volume-dependent at the item level. A subscriber who rents 1.5 items per month generates negative contribution margin. A subscriber who rents 4.2 or more generates positive contribution margin. The distribution of item velocity within the subscriber base determines whether the business is viable.</p>

<p class="article-page__text">Platforms that survived exited mass-market positioning and moved upmarket. The upmarket move serves two functions simultaneously: it increases item value, which improves per-rental revenue, and it concentrates the subscriber base in the high-engagement cohort where item velocity is higher. The trade-off is addressable market size; moving upmarket narrows the pool of potential subscribers.</p>

<h2 class="article-page__h2">The logistics constraint</h2>

<p class="article-page__text">Logistics remains the primary cost lever; platforms without proprietary cleaning infrastructure are at structural disadvantage. The cleaning and preparation cost per item is the unit cost that does not scale. Platforms that outsource this function pay market rates that do not compress as volume grows. Platforms with in-house infrastructure amortise the fixed cost over a larger item base as they scale. The distinction between these two operating models is the primary predictor of whether unit economics improve with scale.</p>

<h2 class="article-page__h2">What the survivors look like</h2>

<p class="article-page__text">The platforms still operating in 2026 share several features: a narrower customer profile with higher-than-average item velocity, higher average item value than their 2019 positioning, in-house or deeply integrated logistics and cleaning capability, and subscriber acquisition cost structures that reflect the actual lifetime value of their target customer rather than the aspiration of the market they originally planned to address. The model works. It works for a smaller market than was originally projected.</p>`,
    pullquote: "\"A subscriber who rents 1.5 items per month generates negative contribution margin. A subscriber who rents 4.2 or more generates positive. That distribution determines everything.\"",
    sources: [
      "Rent the Runway — 10-K filings 2023–2025",
      "Hirestreet — investor update 2025",
      "Company interviews",
      "Euromonitor — Fashion rental market report 2025",
    ],
    related: [
      { slug: "resale-platforms-unit-economics", tag: "Business models", title: "Resale platforms and the unit economics that determine whether the model works at scale", read: "8 min read", date: "12 May 2026", gradient: "linear-gradient(135deg,#141414,#222)" },
      { slug: "consumer-behaviour-gap", tag: "Consumer behaviour", title: "The gap between stated intention and purchasing behaviour in sustainable fashion", read: "14 min read", date: "28 Apr 2026", gradient: "linear-gradient(135deg,#0e0e0e,#1a1a1a)" },
      { slug: "valuation-correction", tag: "Capital", title: "The valuation correction in sustainable fashion and what it reveals about investor assumptions", read: "12 min read", date: "14 Apr 2026", gradient: "linear-gradient(135deg,#131313,#1d1d1d)" },
    ],
  },
};

/* ── Static params ─────────────────────────────────────────────────── */
export function generateStaticParams() {
  return Object.keys(ARTICLES).map((slug) => ({ slug }));
}

/* ── Metadata ──────────────────────────────────────────────────────── */
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const article = ARTICLES[slug];
  if (!article) return { title: "Article not found — Prefall" };
  return {
    title: `${article.title} — Prefall`,
    description: article.dek,
  };
}

/* ── Page ──────────────────────────────────────────────────────────── */
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = ARTICLES[slug];
  if (!article) notFound();

  return (
    <div className="article-page">
      {/* Header */}
      <div className="article-page__header">
        <span className="article-page__tag">{article.tag}</span>
        <h1 className="article-page__title">{article.title}</h1>
        <p className="article-page__dek">{article.dek}</p>
        <div className="article-page__byline">
          <span>Ana Maria Claros</span>
          <span className="card__dot" />
          <span>{article.date}</span>
          <span className="card__dot" />
          <span>{article.read}</span>
        </div>
      </div>

      {/* Hero image */}
      <div className="article-page__image">
        <div className="img-ph" style={{ background: article.gradient }} />
      </div>

      {/* Body */}
      <div className="article-page__body">
        <p className="article-page__lead">{article.lead}</p>

        <div dangerouslySetInnerHTML={{ __html: article.body }} />

        {article.pullquote && (
          <blockquote className="article-page__pullquote">{article.pullquote}</blockquote>
        )}

        {article.figure && (
          <figure className="article-page__figure">
            <div className="img-ph" style={{ background: article.gradient, aspectRatio: "16/9", maxWidth: 720, margin: "0 auto" }} />
            <figcaption>{article.figure.caption}</figcaption>
          </figure>
        )}

        {/* Sources accordion */}
        <div style={{ marginTop: 40 }}>
          <button className="sources-toggle" id="article-sources-btn">
            <span>Sources</span>
            <span className="sources-toggle__icon">↓</span>
          </button>
          <div className="sources-body" id="article-sources">
            <ol>
              {article.sources.map((s, i) => (
                <li key={i}>{s}</li>
              ))}
            </ol>
          </div>
        </div>

        {/* Related articles */}
        <section className="related-section">
          <p className="section__label">Related on Prefall</p>
          <div className="related-carousel">
            <div className="related-grid" id="related-grid">
              {article.related.map((r) => (
                <Link key={r.slug} href={`/articles/${r.slug}`} className="card" style={{ textDecoration: "none" }}>
                  <div className="card__img">
                    <div className="img-ph" style={{ background: r.gradient }} />
                  </div>
                  <div className="card__body">
                    <span className="card__tag">{r.tag}</span>
                    <h3 className="card__title">{r.title}</h3>
                    <div className="card__meta">
                      <span>{r.read}</span>
                      <span className="card__dot" />
                      <span>{r.date}</span>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
            <div className="related-nav">
              <button className="related-nav-btn" aria-label="Previous article">&#8592;</button>
              <button className="related-nav-btn" aria-label="Next article">&#8594;</button>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
