import { defineType, defineField } from "sanity";

export const article = defineType({
  name: "article",
  title: "Article",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (R) => R.required(),
    }),
    defineField({
      name: "tag",
      title: "Tag (display category)",
      description: 'Short label shown on card and article header e.g. "Business models", "Regulation"',
      type: "string",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "readTime",
      title: "Read time",
      description: 'e.g. "8 min read"',
      type: "string",
    }),
    defineField({
      name: "dek",
      title: "Dek (article subheading)",
      description: "Shown on the article page under the title",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "synopsis",
      title: "Synopsis",
      description: "Shown in the article preview modal",
      type: "text",
      rows: 4,
      validation: (R) => R.required(),
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: [
        { type: "block" },
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({ name: "alt", type: "string", title: "Alt text" }),
            defineField({ name: "caption", type: "string", title: "Caption" }),
          ],
        },
      ],
    }),
    defineField({
      name: "keyTakeaways",
      title: "Key Takeaways",
      description: "Bullet points shown in modal and article sidebar",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "sources",
      title: "Primary Sources",
      description: "List of sources shown in modal and article accordion",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "sectors",
      title: "Sectors Implicated",
      description: "Sector tags shown in modal",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "coverImage",
      title: "Cover Image",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "valueChainNodes",
      title: "Value Chain Nodes",
      description: "Which nodes this article covers — controls where it appears throughout the site",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "Raw Materials",      value: "raw-materials" },
          { title: "Yarn & Fabric",      value: "yarn-fabric" },
          { title: "Manufacturing",      value: "manufacturing" },
          { title: "Brands",             value: "brands" },
          { title: "Logistics & Retail", value: "logistics-retail" },
          { title: "Consumer",           value: "consumer" },
          { title: "Secondary Market",   value: "secondary-market" },
        ],
      },
    }),
    defineField({
      name: "featured",
      title: "Featured on homepage",
      description: "Appears in the homepage reading section",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "filterCategory",
      title: "Filter category",
      description: "Controls which filter button shows this article on /articles",
      type: "string",
      options: {
        list: [
          { title: "Business models",     value: "business-models" },
          { title: "Regulation",          value: "regulation" },
          { title: "Consumer behaviour",  value: "consumer-behaviour" },
          { title: "Capital",             value: "capital" },
          { title: "Manufacturing",       value: "manufacturing" },
          { title: "Resale",              value: "resale" },
          { title: "Rental",              value: "rental" },
          { title: "New technologies",    value: "new-technologies" },
          { title: "Brands",              value: "brands" },
        ],
      },
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "tag", media: "coverImage" },
  },
});
